server:
  port: 8080
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/token
            authorization-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/auth
            issuer-uri: http://localhost:7080/realms/reloading
        registration:
          api-gateway:
            provider: keycloak
            client-id: reloading-client
            client-secret: 2EvQuluZfxaaRms8V4NhzBDWzVCSXtty 
            authorization-grant-type: urn:ietf:params:oauth:grant-type:uma-ticket
            scope: 
              - openid
              - email
              - profile
              - roles
  webclient:
    keycloak:
      base-url: http://localhost:7080             
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: loads-service
          uri: lb://loads-service
          predicates:
            - Path=/api/loads/**
          filters:
            - StripPrefix=2
            - TokenForwarding
        - id: rifles-service
          uri: lb://rifles-service
          predicates:
            - Path=/api/rifles/**
          filters:
            - StripPrefix=2
            - TokenForwarding
        - id: fallback-route
          order: 100
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - SetPath=/${path}
            - RewritePath=/(?<segment>.*), /${segment}
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/token
            authorization-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/auth
            issuer-uri: http://keycloak:7080/realms/reloading
        registration:
          api-gateway:
            provider: keycloak
            client-id: reloading-client
            client-secret: 2EvQuluZfxaaRms8V4NhzBDWzVCSXtty 
            authorization-grant-type: urn:ietf:params:oauth:grant-type:uma-ticket
            scope: 
              - openid
              - email
              - profile
              - roles
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans