server:
  port: 8080
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/token
            authorization-uri: http://localhost:7080/realms/reloading/protocol/openid-connect/auth
            issuer-uri: http://localhost:7080/realms/reloading
        registration:
          api-gateway:
            provider: keycloak
            client-id: reloading-client
            client-secret: 2EvQuluZfxaaRms8V4NhzBDWzVCSXtty 
            authorization-grant-type: urn:ietf:params:oauth:grant-type:uma-ticket
            scope: 
              - openid
              - email
              - profile
              - roles
  webclient:
    keycloak:
      base-url: http://localhost:7080             
  reactor:
    context-propagation: AUTO
  cloud:
    gateway:
      routes:
        - id: loads-service
          uri: lb://loads-service
          predicates:
            - Path=/api/loads/**,/api/groups/**,/api/shots/**/loads-service/v3/api-docs
          filters:
            - StripPrefix=1
            - TokenForwarding
            - name: CircuitBreaker
              args:
                name: loadsCircuitBreaker
            - Retry=1
        - id: rifles-service
          uri: lb://rifles-service
          predicates:
            - Path=/api/rifles/**,/rifles-service/v3/api-docs
          filters:
            - StripPrefix=1
            - TokenForwarding
            - name: CircuitBreaker
              args:
                name: riflesCircuitBreaker
            - Retry=1
        - id: fallback-route
          order: 100
          uri: no://op
          predicates:
            - Path=/
          filters:
            - SetPath=/${path}
            - RewritePath=/(?<segment>.*), /${segment}
management:
  otlp:
    tracing:
      endpoint: http://localhost:4317
      transport: grpc
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /rifles-service/v3/api-docs
        name: Rifles Service
        primaryName: Rifles Service
      - url: /loads-service/v3/api-docs
        name: Loads Service
        primaryName: Loads Service
---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/token
            authorization-uri: http://keycloak:7080/realms/reloading/protocol/openid-connect/auth
            issuer-uri: http://keycloak:7080/realms/reloading
        registration:
          api-gateway:
            provider: keycloak
            client-id: reloading-client
            client-secret: 2EvQuluZfxaaRms8V4NhzBDWzVCSXtty 
            authorization-grant-type: urn:ietf:params:oauth:grant-type:uma-ticket
            scope: 
              - openid
              - email
              - profile
              - roles
  webclient:
    keycloak:
      base-url: http://keycloak:7080             
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  otlp:
    tracing:
      endpoint: http://jaeger:4317
      transport: grpc