server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      label: main
      allow-override: true
      override-none: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  tracing:
    sampling:
      probability: 1
#   otlp:
#     metrics:
#       export:
#         step: 30s
#         url: ${OTEL_COLLECTOR_ENDPOINT:http://localhost:4317}
#     tracing:
#       endpoint: ${OTEL_COLLECTOR_ENDPOINT:http://localhost:4317}
#       transport: grpc
#     logging:
#       endpoint: ${OTEL_COLLECTOR_ENDPOINT:http://localhost:4317}
#       transport: grpc 

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/${spring.application.name}/default/${spring.cloud.config.label}/log4j2.xml

log4j2:
  Configuration:
    allowedProtocols: "http,https,file,jar"

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_COLLECTOR_ENDPOINT:http://localhost:4317}
      protocol: grpc
      interval: 10000
