server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      label: main
      allow-override: true
      override-none: true

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/${spring.application.name}/default/${spring.cloud.config.label}/log4j2.xml

management:
  endpoints:
    health:
      probes:
        enabled: true    
    web:
      exposure:
        include: health, info, metrics
  metrics:
    enable:
      all: true
  tracing:
    sampling:
      probability: 1
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/metrics}
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      transport: grpc
    logging:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      transport: grpc 

log4j2:
  Configuration:
    allowedProtocols: "http,https"