server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      allow-override: true
      override-none: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  tracing:
    sampling:
      probability: 1
