server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      allow-override: true
      override-none: true

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    loggers:
      enabled: true
  tracing:
    sampling:
      probability: 1
