server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      label: main
      allow-override: true
      override-none: true
  threads:
    virtual:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:local}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
  observations:
    annotations:
      enabled: true
    enable:
      all: true
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://localhost:4317/v1/logs}
          transport: grpc
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACING_ENDPOINT:http://localhost:4317}
          transport: grpc
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
        step: 10s
  tracing:
    sampling:
      probability: 1

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/${spring.application.name}/default/${spring.cloud.config.label}/log4j2.yaml

log4j2:
  Configuration:
    allowedProtocols: "http,https,file,jar"
