server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      label: main
      allow-override: true
      override-none: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:local}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
    export:
      otlp:
        enabled: true
        url: http://otel-collector:4318/v1/metrics
        step: 10s
        resource-attributes:
          service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/${spring.application.name}/default/${spring.cloud.config.label}/log4j2.yaml

log4j2:
  Configuration:
    allowedProtocols: "http,https,file,jar"

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: grpc
  instrumentation:
    micrometer:
      enabled: true
    runtime-telemetry:
      enabled: false
  metric:
    export:
      interval: 10000
  resource:
    attributes:
      service:
        name: ${spring.application.name}
        version: ${project.version:0.0.8-SNAPSHOT}
  service:
    name: ${spring.application.name}