server:
  port: 0
  shutdown: graceful

spring:
  cloud:
    config:
      label: main
      allow-override: true
      override-none: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  tracing:
    sampling:
      probability: 1
  info:
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true

logging:
  config: ${CONFIG_SERVER_URL:http://localhost:8888}/${spring.application.name}/default/${spring.cloud.config.label}/log4j2.xml

log4j2:
  Configuration:
    allowedProtocols: "http,https,file,jar"

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: grpc
      interval: 10000
  instrumentation:
    common:
      experimental:
        controller-telemetry.enabled: true
    micrometer:
      enabled: true