spring:
  ai:
    mcp:
      server:
        name: reloading-mcp-server
        version: 0.0.7-SNAPSHOT
        type: ASYNC
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
        tool-change-notification: true
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading
          jwk-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761}/eureka/ 
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8083
