server:
  port: 8087

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading/protocol/openid-connect/token
            authorization-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading/protocol/openid-connect/auth
            issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading
            user-info-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:7080}/realms/reloading/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: reloading-client
            client-secret: 2EvQuluZfxaaRms8V4NhzBDWzVCSXtty
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: 
              - openid
              - email
              - profile
              - roles

api:
  gateway:
    base-url: ${API_GATEWAY_URL:http://localhost:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761}/eureka/ 

management:
  otlp:
    tracing:
      endpoint: ${TRACING_SERVER:http://localhost:4317/}
      transport: grpc
